name: Build and deploy Docker Images

on: 
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image for front
      uses: docker/build-push-actions@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest
        context: front
    
    - name: Build & push Docker image for back
      uses: docker/build-push-action@v3
      with:
        context: ./back
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:latest