name: SonarCloud
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud: 
  name: Build and analyze
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 14
  
  - name: Install dependencies
    working-directory: front
    run: npm ci

  - name: Run tests for frontend and generate report
    working-directory: front
    run:  npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: "11"
      distribution: "adopt"
  
  - name: Cache SonarCloud package
    uses: actions/cache@v3
    with:
      path: ~/.sonar/cache
      key: ${{ runner.os }}-sonar
      restore-keys: ${{ runner.os }}-sonar
  
  - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
  
   - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
